install:
  - "echo 'SINATRA setup - start'"
  - "rvm use 2.2.3 --install --binary --fuzzy"
  - "gem install bundler -v 1.11.1"
  - "cd frameworks/sinatra"
  - "bundle install --jobs 3 --frozen --quiet"
  - "cd ../.."
  - "echo 'SINATRA setup - end'"
script:
  - "echo 'SINATRA tests - start'"
  - "cd frameworks/sinatra"
  - "RACK_ENV=test bundle exec ruby tests/**.rb"
  - "cd ../.."
  - "echo 'SINATRA tests - end'"
