install:
  - "echo 'Sinatra setup'"
  - "cd frameworks/sinatra"
  - "rvm use $(more .ruby-version) --install --binary --fuzzy"
  - "gem install bundler -v 1.11.1"
  - "bundle install --jobs 3 --quiet"
  - "cd ../.."

  - "echo 'ExpressJS setup'"
  - "cd frameworks/expressjs"
  - "nvm install $(more .nvmrc) && nvm use $(more .nvmrc)"
  - "npm install"
  - "cd ../.."
script:
  - "cd frameworks/sinatra && ruby tests/app_test.rb && cd ../.."
  - "cd frameworks/expressjs && npm test && cd ../.."
